kind: Service
apiVersion: v1
metadata:
  annotations:
    prometheus.io/probe: 'true'
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort