site_name: 山南溪北Python学习路径
theme:
    name: material
    font:
      text: Noto Serif
      code: Roboto Mono
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material//weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue 
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    features: 
        - navigation.instant #- header.autohide  #自动隐藏
        #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
        - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
        #- navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
        #- navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
        #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
        - navigation.top # 返回顶部的按钮 在上滑时出现
        - search.suggest # 搜索输入一些字母时推荐补全整个单词
        - search.highlight # 搜索出的文章关键词加入高亮
        - navigation.expand # 打开Tab时左侧目录全部展开
        #- navigation.indexes #启用节索引页后，可以将文档直接附加到节
        - search.share #搜索分享按钮
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - bash
        - python
        - golang
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - def_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.caret #下划线
  - pymdownx.mark #文本高亮
  - pymdownx.tilde #删除线
plugins:
    - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'
    # - social:
    #     cards_font: Roboto


extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/
  analytics:
    provider: google
    property: G-144Q0VJMBT
    # property: UA-42618265-2
  
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#cookie-consent
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  
disqus: "xuehaoweng-github-io"
  
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer
social:
- icon: fontawesome/brands/github-alt
    link: https://github.com/xuehaoweng
    name: xuehaoweng
- icon: fontawesome/brands/facebook-f
    link: https://facebook.com/trongvq
    name: trongvq
- icon: fontawesome/brands/linkedin-in
    link: https://www.linkedin.com/in/vqtrong
    name: vqtrong
generator: false # hide the line "Made with Material for MkDocs"
icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
extra_css:
  - assets/view-bigimg.css
  - assets/extra.css
extra_javascript:
  - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'
  - assets/mathjax.js # must be before mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/view-bigimg.js
  - assets/extra.js

  nav:
    # - Home: index.md
    - 基础: base_content/whatispython.md
    - 项目部署: deploy_step/deploy.md