version: '2'
services:
  consul:
    image: consul
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:53/udp
    command: agent -server -client=0.0.0.0 -dev -node=node0 -bootstrap-expect=1 -data-dir=/tmp/consul
    labels:
      SERVICE_IGNORE: 'true'
  registrator:
    image: gliderlabs/registrator
    depends_on:
      - consul
    volumes:
      - /var/run:/tmp:rw
    command: consul://consul:8500
  prometheus:
    image: quay.io/prometheus/prometheus
    ports:
      - 9090:9090
    volumes:
      # - ./prometheus/prometheus_static.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus_consul.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ~/grafana/:/var/lib/grafana:rw
  node_exporter:
    image: quay.io/prometheus/node-exporter
    pid: "host"
    ports:
      - 9100:9100
    labels:
      SERVICE_TAGS: "development"
      SERVICE_NAME: "node_exporter"
      SERVICE_TAG_IO_PROMETHEUS_SCRAPED: "true"
  docker_exporter:
    image: wisecity/docker-metrics-exporter
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:rw
    labels:
      SERVICE_TAGS: "production"
  # cadvisor:
  #   image: google/cadvisor:latest
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - /:/rootfs:ro 
  #     - /var/run:/var/run:rw
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   labels:
  #     SERVICE_TAGS: "production,scraped"
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ~/jenkins_home/:/var/jenkins_home/:rw
    labels:
      SERVICE_NAME: "jenkins"
      SERVICE_8080_NAME: "jenkins"
      SERVICE_8080_PORT: "8080"
      SERVICE_50000_IGNORE: "true"
