global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: node
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - node_exporter:9100
- job_name: docker
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - docker_exporter:9095
- job_name: cadvisor
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - cadvisor:8080
