/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "从零开始学Golang",
  "description": "从零开始学Golang",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/golang.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "基本数据类型",
      "frontmatter": {},
      "regularPath": "/pages/article/test3.html",
      "relativePath": "pages/article/test3.md",
      "key": "v-8067cf10",
      "path": "/pages/article/test3.html",
      "headers": [
        {
          "level": 2,
          "title": "基本数据类型",
          "slug": "基本数据类型"
        },
        {
          "level": 2,
          "title": "Go内置七个基本数据类型(20个子类型)",
          "slug": "go内置七个基本数据类型-20个子类型"
        },
        {
          "level": 3,
          "title": "1.0. 布尔类yushengming型",
          "slug": "_1-0-布尔类yushengming型"
        },
        {
          "level": 3,
          "title": "1.1. 整型",
          "slug": "_1-1-整型"
        },
        {
          "level": 3,
          "title": "1.2. 浮点型",
          "slug": "_1-2-浮点型"
        },
        {
          "level": 3,
          "title": "1.3. 复数类型",
          "slug": "_1-3-复数类型"
        },
        {
          "level": 3,
          "title": "1.4. 字符串",
          "slug": "_1-4-字符串"
        },
        {
          "level": 3,
          "title": "1.5. rune 类型",
          "slug": "_1-5-rune-类型"
        }
      ]
    },
    {
      "title": "从零开始学Golang",
      "frontmatter": {
        "home": true,
        "title": "从零开始学Golang",
        "heroImage": "/golang.png",
        "heroText": "从零开始学Golang",
        "tagline": "python 转 golang 学习路径",
        "actionText": "快速开始 →",
        "actionLink": "/guide/getting-started.html",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "本文档内容版权为 NetAxe 官方团队及贡献者所有，保留所有权利。"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-e08ec56e",
      "path": "/"
    },
    {
      "title": "GO语言基础知识",
      "frontmatter": {},
      "regularPath": "/pages/article/test2.html",
      "relativePath": "pages/article/test2.md",
      "key": "v-d6714950",
      "path": "/pages/article/test2.html",
      "headers": [
        {
          "level": 2,
          "title": "Go语言中的变量和常量",
          "slug": "go语言中的变量和常量"
        },
        {
          "level": 2,
          "title": "1.变量",
          "slug": "_1-变量"
        },
        {
          "level": 3,
          "title": "1.1. 变量显示声明",
          "slug": "_1-1-变量显示声明"
        },
        {
          "level": 3,
          "title": "1.2. 变量短类型声明",
          "slug": "_1-2-变量短类型声明"
        },
        {
          "level": 3,
          "title": "1.3. 变量总结",
          "slug": "_1-3-变量总结"
        },
        {
          "level": 2,
          "title": "2. 常量",
          "slug": "_2-常量"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/getting-started.html",
      "relativePath": "guide/getting-started.md",
      "key": "v-24207976",
      "path": "/guide/getting-started.html",
      "headers": [
        {
          "level": 3,
          "title": "目录",
          "slug": "目录"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/pages/article/test1.html",
      "relativePath": "pages/article/test1.md",
      "key": "v-69c29e38",
      "path": "/pages/article/test1.html",
      "headers": [
        {
          "level": 2,
          "title": "1. Go语言 简介",
          "slug": "_1-go语言-简介"
        },
        {
          "level": 2,
          "title": "2. Go语言特性",
          "slug": "_2-go语言特性"
        },
        {
          "level": 2,
          "title": "3. 学习新语言",
          "slug": "_3-学习新语言"
        },
        {
          "level": 2,
          "title": "4. 初识Go程序",
          "slug": "_4-初识go程序"
        },
        {
          "level": 2,
          "title": "5. Go语言词法单元",
          "slug": "_5-go语言词法单元"
        },
        {
          "level": 3,
          "title": "5.0 token解释",
          "slug": "_5-0-token解释"
        },
        {
          "level": 3,
          "title": "5.1 标识符",
          "slug": "_5-1-标识符"
        },
        {
          "level": 3,
          "title": "5.2 操作符",
          "slug": "_5-2-操作符"
        },
        {
          "level": 3,
          "title": "5.3 字面常量",
          "slug": "_5-3-字面常量"
        },
        {
          "level": 2,
          "title": "篇0总结",
          "slug": "篇0总结"
        }
      ]
    },
    {
      "title": "复合数据类型",
      "frontmatter": {},
      "regularPath": "/pages/article/test4.html",
      "relativePath": "pages/article/test4.md",
      "key": "v-2a5e54d0",
      "path": "/pages/article/test4.html",
      "headers": [
        {
          "level": 3,
          "title": "复合数据类型",
          "slug": "复合数据类型"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/golang.png",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "分类",
        "ariaLabel": "分类",
        "items": [
          {
            "text": "文章",
            "link": "/pages/article/test1.md"
          },
          {
            "text": "琐碎",
            "link": "/pages/folder2/test4.md"
          }
        ]
      },
      {
        "text": "文档",
        "items": [
          {
            "text": "Python菜鸟",
            "link": "https://www.runoob.com/python3/python3-tutorial.html"
          },
          {
            "text": "Go菜鸟",
            "link": "https://www.runoob.com/go/go-tutorial.html"
          },
          {
            "text": "快速上手",
            "link": "https://github.com/example/NetAxea"
          }
        ]
      },
      {
        "text": "Django",
        "link": "https://docs.djangoproject.com/zh-hans/3.2/"
      },
      {
        "text": "Gin",
        "link": "https://www.topgoer.com/gin%E6%A1%86%E6%9E%B6/"
      }
    ],
    "sidebar": {
      "/pages/article/": [
        {
          "title": "常见问题test_知识库",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            {
              "title": "test1",
              "path": "test1"
            },
            {
              "title": "test2",
              "path": "test2"
            },
            {
              "title": "test3",
              "path": "test3"
            },
            {
              "title": "test4",
              "path": "test4"
            }
          ]
        }
      ],
      "/": [
        ""
      ]
    }
  }
}