site_name: 跟 "山南溪北" 学Python

theme:
    name: material
    font:
        text: Roboto
    logo: /assets/flask-icon.png
    favicon: /assets/flask-icon.png
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material//weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    features: 
        - navigation.instant #- header.autohide  #自动隐藏
        #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
        - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
        #- navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
        #- navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
        #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
        - navigation.top # 返回顶部的按钮 在上滑时出现
        - search.suggest # 搜索输入一些字母时推荐补全整个单词
        - search.highlight # 搜索出的文章关键词加入高亮
        - navigation.expand # 打开Tab时左侧目录全部展开
        #- navigation.indexes #启用节索引页后，可以将文档直接附加到节
        - search.share #搜索分享按钮
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - bash
        - python
        - golang
icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
site_url: https://LearnPython.com/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - def_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.caret #下划线
  - pymdownx.mark #文本高亮
  - pymdownx.tilde #删除线
plugins:
    - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'
nav:
    - 首页: index.md
    - 关于我: about_me.md
    - License: license.md
    - Python基础:
        - 语言介绍: python_base/language_introduce.md
        - 第一个Python程序: python_base/first_python_program.md
        - 数据类型: python_base/datatype.md
        - 控制结构: python_base/control_struct.md
        - 函数:  python_base/function.md
        - 类:  python_base/class.md
    - Python高级:
        - 对象: python_advance/object.md
    - Python Web开发:
        - Python Flask:
          - Flask简介: python_web/python_flask/index.md
          - Flask安装: python_web/python_flask/install_flask.md
          - Flask快速开始: python_web/python_flask/quicklystart.md
        - Python Django:
          - Django简介: python_web/python_django/index.md
        - Python FastApi:
          - FastApi简介: python_web/python_fastapi/index.md

# theme: readthedocs